if: NOT (commit_message =~ /^\[docs\]/)

language: node_js
os: linux
dist: xenial
jobs:
  include:
    - node_js: "10"
      env: GULP_TASK="test-functional-travis-desktop-osx-and-ms-edge"
  fast_finish: true

cache:
  directories:
    - $HOME/.npm

install: travis_retry npm install

branches:
  except:
    - /^build-bot-temp-.*$/
    - /^\(testbot-only\)/
    - new-docs

notifications:
  email: false
